    <div class="form-group<? if(!$item->isValid()) echo ' has-error'; ?>">
        <label for="<?=$item->id ?>"><?=$item->title ?></label>
        <select <?=$item->addCssClass('form-control')->attributes?>>
        <? foreach($item as $option): ?>
        <option value="<?= $option->key ?>"<?= $option->selected ? ' selected="selected"' : '' ?>><?= $option ?></option>
        <? endforeach ?>
        </select>
        <? if(!$item->isValid()): ?>
        <? foreach($item->messages as $error): ?>
        <span class="help-inline"><?= $error ?></span>
        <? endforeach ?>
        <? elseif($item->description): ?>
        <span class="help-inline"><?= $item-description ?></span>
        <? endif ?>
    </div>