<? $item->setAttribute('role','form') ?>
<form <?= $item->attributes ?>>
<? $i = 0; $last = (count($item->fields->fieldLists())-1); $isTabbed = FALSE; ?>
<? foreach($item->fields->fieldLists() as $field): ?>
    <? if($field->switchable): ?>
        <? $isTabbed = TRUE ?>
        <? if($i == 0): ?>
        <ul id="tabs-<?= $item->id ?>" class="nav nav-tabs">
        <? endif ?>
        <li<? if($i == 0): ?> class="active"<? endif ?>><a href="#<?= $field->id ?>" data-toggle="tab"><?= $field->title ?></a></li>
        <? if($i == $last): ?>
        </ul>
        <? endif ?>
    <? $i++ ?>
    <? else: ?>
    <?= $field->className ?>
    <? endif ?>
<? endforeach ?>
<? if($isTabbed): ?>
<div class="tab-content">
<? endif ?>
<? $i = 0 ?>
<? foreach($item->fields as $field): ?>
    <? if($i==0 && $field->className == 'FieldList'): ?>
        <? $field->isFirst = TRUE; ?>
        <? $i++ ?>
    <? else: ?>
        <? $field->isFirst = FALSE; ?>
    <? endif ?>
    <? if($field->className == 'HiddenField'): ?>
       <input <?=$field->attributes ?> />
    <? else: ?>
       <?= $field ?>
       <? endif ?>
<? endforeach ?>
<? if($isTabbed): ?>
</div>
<? endif ?>
<? foreach($item->actions as $field): ?>
    <button type="submit" value="<?= $field->action ?>" class="<?= $field->cssClasses->append('btn')->append('btn-primary') ?>"><?= $field->title ?></button>
<? endforeach ?>
</form>