<? $item->setAttribute('role','form') ?>
<form <?= $item->attributes ?>>
<? $isTabbed = FALSE; ?>
<? foreach($item->fields->fieldLists() as $field): ?>
    <? if($field->switchable): ?>
        <? $isTabbed = TRUE ?>
        <? if($field->isFirstList()): ?>
        <ul id="tabs-<?= $item->id ?>" class="nav nav-tabs">
        <? endif ?>
        <li<? if($field->isFirstList()): ?> class="active"<? endif ?>><a href="#<?= $field->id ?>" data-toggle="tab"><?= $field->title ?></a></li>
        <? if($field->isLastList()): ?>
        </ul>
        <? endif ?>
    <? else: ?>
    <?= $field->className ?>
    <? endif ?>
<? endforeach ?>
<? if($isTabbed): ?>
<div class="tab-content">
<? endif ?>
<? foreach($item->fields as $field): ?>
    <? if($field->className == 'HiddenField'): ?>
       <input <?=$field->attributes ?> />
    <? else: ?>
       <?= $field ?>
       <? endif ?>
<? endforeach ?>
<? if($isTabbed): ?>
</div>
<? endif ?>
<? foreach($item->actions as $action): ?>
    <button type="submit" name="<?= $action->action ?>" value="<?= $action->value ?>" class="<?= $action->cssClasses->append('btn')->append('btn-primary') ?>"><?= $action->title ?></button>
<? endforeach ?>
</form>