    <div class="form-group<? if(!$item->isValid()) echo ' has-error'; ?>">
        <label for="<?=$item->id ?>"><?=$item->title ?></label>
        <? if($item->className == 'SelectOneField'): ?>
            <select <?=$item->addCssClass('form-control')->attributes?>>
            <? foreach($item as $option): ?>
            <option value="<?= $option->key ?>"<?= $option->selected ? ' selected="selected"' : '' ?>><?= $option ?></option>
            <? endforeach ?>
            </select>
        <? elseif($item->className == 'RadioButtonsField'): ?>
            <? foreach($item as $option): ?>
                <div class="radio">
                    <label><input type="radio" name="<?=$item->name ?>" value="<?= $option->key ?>" <?= $option->selected ? ' checked="checked"' : '' ?>/> <?= $option ?></label>
                </div>
            <? endforeach ?>
        <? endif ?>
        <? if(!$item->isValid()): ?>
        <? foreach($item->messages as $error): ?>
        <span class="help-inline"><?= $error ?></span>
        <? endforeach ?>
        <? elseif($item->description): ?>
        <span class="help-inline"><?= $item-description ?></span>
        <? endif ?>
    </div>