<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample Template</title>

    <!-- Bootstrap -->
    <link href="themes/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="themes/bootstrap/js/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        div.tab-pane{
            margin-top: 10px;
        }
        div.tab-content{
            margin-bottom: 20px;
        }
    </style>
  </head>
  <body>
    <div class="container">
    <h1>Simple Bootstrap Form</h1>
    <?= $form ?>
    <? if($data): ?>
    <br/><h3>Data:</h3>
    <pre><? var_export($data) ?></pre>
    <? endif ?>
    <? if($form->selectedAction): ?>
    <br/><h3>Action:</h3>
    <code><?= $form->selectedAction->getValue() ?></code>
    <? endif ?>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="themes/bootstrap/js/bootstrap.min.js"></script>
    <script src="themes/bootstrap/js/inline-edit.js"></script>
    <!-- script src="themes/bootstrap/js/bootstrap3-editable/js/bootstrap-editable.min.js"></script -->
  </body>
</html>